### ISSUE TITLE
[請益] 交易失敗， 443 端口設定

### ISSUE THREAD

**Issue by andy0025681** [hsuanchi/flask-ecpay#1]
感謝您分享優質文章，受益良多

我目前使用heroku作為domain，始終無法在測試環境交易成功，卡在以下錯誤:

  交易失敗 Transaction failed
  訊息代碼 Message code：10200141
  常見失敗原因如下 Frequently seen causes for failure as below
  商店尚未開啟收款服務，請聯繫商店處理。 The merchant has not activated payment collection service.
  交易金額低於下限或超過上限 Transaction is less than lower limit or more than upper limit.
  此商店未提供任何付款方式，請聯繫商店處理。 The store does not provide any payment method. Please contact the merchant.
  此商店所傳送串接參數錯誤，請聯繫商店處理。 Incorrect parameter. Please contact the merchant.
  建議您先與購買商品的商家或購物網站業者聯繫 Suggest contact with seller of the merchandize or online shop first!

是否下列原因都有可能造成錯誤，還請前輩指點:
1. 目前未設定443 端口: 請問您是如何監聽443端口的呢? 
2. 官網程式提供的MerchantID以及密鑰無法使用，必須申請帳號才能測試

**Comment by hsuanchi** [comment]
嗨，你好

> 1. 目前未設定443 端口: 請問您是如何監聽443端口的呢?

443 port 可以試試用 [ngrok](https://ngrok.com/) 處理喲

> 2.官網程式提供的MerchantID以及密鑰無法使用，必須申請帳號才能測試

我記得寫這份時，是可以用測試 `MerchantID` 參數的喲

```
            self.params = {
                'MerchantID':
                '2000132',
                'HashKey':
                '5294y06JbISpM5x9',
                'HashIV':
                'v77hoKGq4kWxNNIS',
                'action_url':
                'https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5'
            }
```

**Comment by andy0025681** [comment]
非常感謝您
